-- MySQL Script generated by MySQL Workbench
-- Tue Sep  1 11:33:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion_nettoyage_classes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_nettoyage_classes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_nettoyage_classes` DEFAULT CHARACTER SET utf8 ;
USE `gestion_nettoyage_classes` ;

-- -----------------------------------------------------
-- Table `gestion_nettoyage_classes`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_nettoyage_classes`.`classes` ;

CREATE TABLE IF NOT EXISTS `gestion_nettoyage_classes`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classe_name` VARCHAR(20) NOT NULL,
  `classroom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `classe_name_UNIQUE` (`classe_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_nettoyage_classes`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_nettoyage_classes`.`students` ;

CREATE TABLE IF NOT EXISTS `gestion_nettoyage_classes`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `class_id` INT NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_students_classes_idx` (`class_id` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `classes_id_UNIQUE` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_classes`
    FOREIGN KEY (`class_id`)
    REFERENCES `gestion_nettoyage_classes`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_nettoyage_classes`.`plannings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gestion_nettoyage_classes`.`plannings` ;

CREATE TABLE IF NOT EXISTS `gestion_nettoyage_classes`.`plannings` (
  `id` INT NOT NULL,
  `week_date` DATE NOT NULL,
  `is_done` TINYINT(1) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `week_date_UNIQUE` (`week_date` ASC) VISIBLE,
  INDEX `fk_plannings_students1_idx` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `students_ID_UNIQUE` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_plannings_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gestion_nettoyage_classes`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
